version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: banking-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: banking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - banking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking_user -d banking_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  banking-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local