### Get all customers
GET http://localhost:8080/api/v1/customers

### Get customer by email - John Doe
GET http://localhost:8080/api/v1/customers/john.doe@example.com

### Get customer by email - Jane Smith
GET http://localhost:8080/api/v1/customers/jane.smith@example.com

### Get customer by email - GG
GET http://localhost:8080/api/v1/customers/gg@gmail.com

### Create a new customer
POST http://localhost:8080/api/v1/customers
Content-Type: application/json

{
  "first_name": "Sonia",
  "last_name": "Gkezeri",
  "email": "sg@gmail.com",
  "phone": "69999987"
}

### Get customer by email - sg
GET http://localhost:8080/api/v1/customers/sg@gmail.com